version: '3.8'
services:
  mongodb:
    image: mongo:7-jammy
    ports:
      - 27017:27017
    volumes:
      - dbdata:/data/db
    environment:
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
  tommy:
    build: ./
    restart: always
    links:
      - mongodb
    environment:
      - token=${TOKEN}
      - guildID=${GUILDID}
      - clientID=${CLIENTID}
      - db_host=mongodb
      - db_name=${MONGO_INITDB_DATABASE}
volumes:
  dbdata: