CREATE TABLE IF NOT EXISTS "Users" (
	"ID"	INTEGER NOT NULL UNIQUE,
	"Name"	TEXT NOT NULL,
	"JoinDate"	INTEGER NOT NULL,
	"CreatedDate"	INTEGER NOT NULL,
	"PrimaryRole"	INTEGER NOT NULL,
	PRIMARY KEY("ID"),
	FOREIGN KEY("PrimaryRole") REFERENCES "Roles"("ID") ON UPDATE CASCADE
);
CREATE TABLE IF NOT EXISTS "Roles" (
	"Name"	TEXT NOT NULL,
	"ID"	INTEGER NOT NULL UNIQUE,
	"Color"	TEXT NOT NULL,
	"Priority"	INTEGER NOT NULL UNIQUE,
	PRIMARY KEY("ID")
);
CREATE TABLE IF NOT EXISTS "Dailies" (
	"User"	INTEGER NOT NULL UNIQUE,
	"DailyUses"	INTEGER NOT NULL,
	"LastDaily"	INTEGER NOT NULL,
	FOREIGN KEY("User") REFERENCES "Users"("ID") ON UPDATE CASCADE,
	PRIMARY KEY("User")
);
CREATE TABLE IF NOT EXISTS "Credits" (
	"User"	INTEGER NOT NULL UNIQUE,
	"Credits"	INTEGER NOT NULL,
	PRIMARY KEY("User"),
	FOREIGN KEY("User") REFERENCES "Users"("ID") ON UPDATE CASCADE
);
CREATE TABLE "Warnings" (
	"User"	INTEGER NOT NULL,
	"Reason"	TEXT NOT NULL,
	"Date"	INTEGER NOT NULL,
	"WarnedBy"	INTEGER NOT NULL,
	"WarnID"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	FOREIGN KEY("User") REFERENCES "Users"("ID") ON UPDATE CASCADE,
	FOREIGN KEY("WarnedBy") REFERENCES "Users"("ID") ON UPDATE CASCADE
);
CREATE TABLE IF NOT EXISTS "Levels" (
	"User"	INTEGER NOT NULL UNIQUE,
	"Level"	INTEGER NOT NULL,
	"Points"	INTEGER NOT NULL,
	"MonthLevel"	INTEGER NOT NULL,
	"MonthPoints"	INTEGER NOT NULL,
	PRIMARY KEY("User"),
	FOREIGN KEY("User") REFERENCES "Users"("ID") ON UPDATE CASCADE
);
